### ISSUE TITLE
userspace_touch_driver.sh - hardcoeded i2c channel

### ISSUE THREAD

**Issue by MM2forever** [optisimon/ft5406-capacitive-touch#1]
Hey there,

it seems in line 131
`STR=$(i2cdump -y -r 3-6 1 0x38 bc \`

you have hardcoded the i2c bus to 1 - for most user it most likely isn't a problem because the use bus 1 anyways, but it kind of defeats the purpose of making it a variable in all the other places.

Thanks,

Christian

**Comment by optisimon** [comment]
Thanks, just fixed it
