### ISSUE TITLE
Help with reproduction

### ISSUE THREAD

**Issue by tibor-vavra** [optisimon/ft5406-capacitive-touch#2]
Hello,
I like your project but I cant try it by myself. I already have i2c1 ready on rpi3, my device is on adress 45 but CapacityVisualizer have black screen and I have no idea what to do.

Thanks for help

**Comment by optisimon** [comment]
Hi,

1) Did the touchscreen work (as a touchscreen) before you tried to set things up to use this tool?

2) I need to know some information about your system before I can start asking the right questions. So I would need the output of these commands:
uname -a
lsb_release -a
cat /proc/cmdline
cat /boot/cmdline.txt
cat /boot/config.txt
dmesg | grep i2c

/Simon

**Comment by tibor-vavra** [comment]
1. At start yes, now I set disable_touchscreen=1 in /boot/config.txt. But your script userspace_touch_driver.sh is emulating touch screen(coordinate system is mirrored).

2. 
#### uname -a
 Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux

 #### lsb_release -a
 No LSB modules are available.
 Distributor ID:	Raspbian
 Description:	Raspbian GNU/Linux 8.0 (jessie)
 Release:	8.0
 Codename:	jessie

#### cat /proc/cmdline
8250.nr_uarts=0 bcm2708_fb.fbwidth=800 bcm2708_fb.fbheight=480 bcm2708_fb.fbswap=1 dma.dmachans=0x7f35 bcm2709.boardrev=0xa02082 bcm2709.serial=0xb489aa49 bcm2709.uart_clock=48000000 smsc95xx.macaddr=B8:27:EB:89:AA:49 vc_mem.mem_base=0x3dc00000 vc_mem.mem_size=0x3f000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=PARTUUID=bcef204e-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles

#### cat /boot/cmdline.txt
dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=PARTUUID=bcef204e-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles

#### cat /boot/config.txt
disable_touchscreen=1
force_eeprom_read=0
dtparam=i2c_arm=on

\# For more options and information see
\# http://rpf.io/configtxtreadme
\# Some settings may impact device functionality. See link above for details

\# uncomment if you get no picture on HDMI for a default "safe" mode
\#hdmi_safe=1

\# uncomment this if your display has a black border of unused pixels visible
\# and your display can output without overscan
disable_overscan=1

\# uncomment the following to adjust overscan. Use positive numbers if console
\# goes off screen, and negative if there is too much border
\#overscan_left=16
\#overscan_right=16
\#overscan_top=16
\#overscan_bottom=16

\# uncomment to force a console size. By default it will be display's size minus
\# overscan.
\#framebuffer_width=1280
\#framebuffer_height=720

\# uncomment if hdmi display is not detected and composite is being output
\#hdmi_force_hotplug=1

\# uncomment to force a specific HDMI mode (this will force VGA)
\#hdmi_group=1
\#hdmi_mode=1

\# uncomment to force a HDMI mode rather than DVI. This can make audio work in
\# DMT (computer monitor) modes
\#hdmi_drive=2

\# uncomment to increase signal to HDMI, if you have interference, blanking, or
\# no display
\#config_hdmi_boost=4

\# uncomment for composite PAL
\#sdtv_mode=2

\#uncomment to overclock the arm. 700 MHz is the default.
\#arm_freq=800

\# Uncomment some or all of these to enable the optional hardware interfaces
dtparam=i2c_arm=on
dtparam=i2s=on
\#dtparam=spi=on

\# Uncomment this to enable the lirc-rpi module
\#dtoverlay=lirc-rpi

\# Additional overlays and parameters are documented /boot/overlays/README

\# Enable audio (loads snd_bcm2835)
\#dtparam=audio=on

#### dmesg | grep i2c
[    3.586780] i2c /dev entries driver
[    4.656455] bcm2708_i2c 3f804000.i2c: BSC1 Controller at 0x3f804000 (irq 83) (baudrate 100000)

**Comment by optisimon** [comment]
Thanks,

Replies:

1) Excellent test, shows that everything is connected, and that we actually can talk to the touch controller.

2) I did have a "lcd_rotate=2" in my  /boot/config.txt (to fit the casing), probably explains why userspace_touch_driver.sh don't use the correct coordinate system for you (maybe I'll create an option to rotate things in that script)
-----
New questions:

3) I would really want the complete output from running **dump_all_registers.sh**.<br>
That will show FW revision of the controller. My have firmware ID 0x0B, stored in register "Operating, address 0xA6", and firmware library version 0x30.0x03 stored in 0xA1,0xA2. <br>
My best guess would be that they've changed firmware in the touch controller, and that we now need to read out the raw capacitance values in a different way. <br>
I do remember seeing some other ways to read out raw capacitance values for the same chip that didn't work on my raspberry pi touch screen. It might be easy to fix if I can get hold of a screen with your firmware. Or I could make an experiment branch with some tests for you (but that will have much slower progress)

4) When and where did you buy that screen?

**Comment by tibor-vavra** [comment]
### dump_all_registers.sh

    Register dump (Operating):
         0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f    0123456789abcdef
    00: 00 00 00 40 a3 01 54 00 00 ff ff ff ff ff ff ff    ...@??T.........
    10: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff    ................
    20: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff    ................
    30: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 00    ................
    40: 01 81 54 00 a3 00 00 ff ff ff ff ff ff ff ff ff    ??T.?...........
    50: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff    ................
    60: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff    ................
    70: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff    ................
    80: 2d 2d 12 14 11 a0 01 05 00 1e 00 01 00 00 00 00    --??????.?.?....
    90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 22    ..............."
    a0: 13 00 02 54 01 01 0b 01 79 01 0c 00 00 01 01 0a    ?.?T????y??..???
    b0: 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 55    .?.............U
    c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
    d0: 00 00 00 00 00 00 00 00 00 00 00 00 17 0d 00 0a    ............??.?
    e0: ff ff ff ff ff ff ff ff ff ff ff eb 08 ff ff ff    ...........??...
    f0: ff ff ff ff ff ff ff ff ff ff ff ff 01 00 32 ff    ............?.2.


    Register dump (Test):
         0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f    0123456789abcdef
    00: 40 00 17 0d 00 0a 00 00 00 00 00 00 00 00 00 00    @.??.?..........
    10: 00 00 00 00 00 00 01 c8 1e 00 00 00 00 00 40 64    ......???.....@d
    20: 04 49 2e 01 00 00 00 00 00 00 00 00 00 00 00 01    ?I.?...........?
    30: f4 19 32 00 00 01 00 02 6e 6e 6e 6e 00 02 00 02    ??2..?.?nnnn.?.?
    40: 10 25 03 80 01 00 00 00 00 00 00 00 00 00 00 02    ?%???..........?
    50: 00 8f fe 00 00 00 00 00 00 00 00 00 41 42 00 00    .??.........AB..
    60: 1d 17 01 07 18 07 05 01 11 5d 7b 01 01 00 00 00    ?????????]{??...
    70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
    80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
    90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
    a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
    b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
    c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
    d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
    e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
    f0: 00 00 00 00 00 00 00 00 00 00 00 01 00 00 00 00    ...........?....



### I buy it in Alza.cz (something like Amazon but for central Europe). Its looklike original one and they say its oficial touch display...
https://www.alza.de/raspberry-pii-touch-display-7-d4268133.htm
https://www.alza.cz/raspberry-pii-touch-display-7-d4268133.htm

**Comment by tibor-vavra** [comment]
Did you find anything? This is a screenshot of CapacitanceVisualizer running on my device.

![screenshot](https://user-images.githubusercontent.com/4319021/27175179-a50a3b9e-51be-11e7-9415-b559c239a9d5.png)

**Comment by tibor-vavra** [comment]
I found what problem is!!! Controller for my capacitive touch screen is FT5426DQ8, it has different parameters :-). 

Can you help me with creating new version of CapacitanceVisualizer? 

This is link to documentation for this controller:
https://www.newhavendisplay.com/appnotes/datasheets/touchpanel/FT5x26.pdf

**Comment by optisimon** [comment]
I'm thinking of trying to source a raspberry pi touch screen with that FT5426 controller, but due to vacations etc I can't order it right now.

I think I have a fairly good chance of getting it to work even without access to proper documentation, but I might not be able to read out the values as fast as possible.

Your link is just the regular data sheet, mostly electrical, and don't contain any information for programmers. With documentation of the registers in that chip, it would be much easier (something like https://www.newhavendisplay.com/appnotes/datasheets/touchpanel/FT5x06_registers.pdf but for your touch controller)

But I for sure would need a day or two with direct access to a display. (Unless they decided to make it really hard, or even next to impossible to read out raw touch values from that chip).

**Comment by optisimon** [comment]
Closed / Won't Fix this for now (I'm regarding ourselves as incompatible, readme updated).

Will spend some time in the middle of July to try and get raw measurement values out from the new display with the new chip.

If that succeeds, I'll try to include the solution in this codebase

**Comment by ghost** [comment]
Currently, the FT5406 touch screen is difficult to buy. 
I'm also wondering how to get raw measurement values by using FT5426 controller. 
I'm really glad if you share any updates.
